name: .NET NuGet Pack main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.302
      - name: Setup dotnet tools
        run: dotnet tool restore
      - name: Test
        run: ./build.sh --target test --no-logo
  pack:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.302
      - name: Setup dotnet tools
        run: dotnet tool restore
      - name: Pack
        run: ./build.sh --no-logo --version 0.0.0-dev.${GITHUB_SHA::8} --release-notes 'This is a package built from main branch.' --target Pack
      - uses: actions/upload-artifact@v3
        with:
          name: nuget-package
          path: artifacts/*.nupkg
